### ISSUE TITLE
Database Table email_log

### ISSUE THREAD

**Issue by Rootes** [cloudest-co/laravel-nova-email-log#1]
Hello,
Sorry I am a big noob, Can you add the Table Migration? I am not sure what fields I need to add in that table for make it running.

Thanks in Advance and sorry if the issue is too stupid, I am more a dancer than a programmer to be honest. I am just making the website of my dance school. ;)

**Comment by floh1111** [comment]
Hi @Rootes, this package depends on the package `cloudest-co/laravel-eloquent-email-log` which contains the database migration.
